print recepisse
OpenSourcePolitics/decidim-cese pull request #27
Opened 2023-03-13 10:32 UTC by eliegaboriau

2023-03-14 12:44 UTC, Quentinchampenois requested changes
Thank you for this feature, I have a suggestion about the base64 images

Is there a reason for overriding rather than add extends controller and permissions ?

2023-03-14 14:33 UTC, eliegaboriau commented on app/views/decidim/initiatives/initiatives/print.html.erb
> +      <img src="data:image/png;base64,<%= ENV["IMG_SIGNATURE"] %>", width="250"/>
It should be okay now

2023-03-14 17:26 UTC, Quentinchampenois requested changes
Thanks for the changes, I made a mistake on the previous change request, current permissions extend isn't taken in account at runtime 

I think we should : 
- [ ] keep the override for the permissions
- [ ] extend Controller to expose `helper_method: i18n_options` because it saves and expose `@i18n_options`
- [ ] In method `i18n_options` we should extract `authorization` and `name` in another private method which returns authorization.name or author.name (same condition but outside method)
- [x] Helpers for images looks good and works fine locally 
- [ ] Add specs for helpers to be sure img tag is well generated and test with a non-valid base64 format

Sorry for the double change request, I remain available
Also, we must discuss about how to deal with base64 image before merging

2023-03-20 14:12 UTC, Quentinchampenois approved these changes

2023-03-20 16:05 UTC, luciegrau approved these changes

2023-03-20 16:09 UTC, merged