Uploader images recepisse
OpenSourcePolitics/decidim-cese pull request #33
Opened 2023-04-05 09:22 UTC by eliegaboriau

#### :tophat: Description
*Please describe your pull request.*

This PR changes the way images are handled in the recepisse.
They now mus be uploaded in the organization's appearance settings, and are displayed in the recepisse.

#### Testing
*Describe the best way to test or validate your PR.*

Example:
- Go to the organization appearance settings
- Add cachet image and signature image
- Publish a petition you created
- Click on "voir le recepisse"
- See your images

#### Tasks
- [x] Add specs

2023-04-05 12:48 UTC, luciegrau approved these changes
LGTM thanks Elie ! 🍂

2023-04-06 15:13 UTC, Quentinchampenois requested changes
Nice work it works great, I think it is the best alternative we have ! 

I just have a little change request about the migration, we should ensure now that we can revert migration before running in database

2023-04-06 15:13 UTC, Quentinchampenois commented on db/migrate/20230404130043_add_secrets_image_to_organization.rb
> +class AddSecretsImageToOrganization < ActiveRecord::Migration[6.1]
We should allow reversibility of this migration by adding columns in `up` method and removing columns in `down` method

2023-04-06 15:39 UTC, Quentinchampenois approved these changes
Nice feature !

2023-04-06 15:45 UTC, merged