[Feature] - Add Matomo's cookies config to CESE
OpenSourcePolitics/decidim-cese pull request #35
Opened 2023-04-12 10:35 UTC by AyakorK

## Description

This PR is made to add matomo's cookies management to the CESE according to the 0.27 version of Decidim

## Related Issues

This card [Notion](https://www.notion.so/opensourcepolitics/CESE-Cookies-f85befdaa5e641e593fcc395ea10f9db?pvs=4)

2023-04-13 10:38 UTC, paulinebessoles commented
Hi @AyakorK thank you for the PR! 
I have one feedback after reviewing in local, I think the Matomo cookie should appear on the cookie modal in the Analytics section, which is not the case right now:
<img width="607" alt="Capture d’écran 2023-04-13 à 12 36 00" src="https://user-images.githubusercontent.com/52420208/231733822-12dc12f3-046f-4731-903f-1199c5282c1e.png">

I think that in order to do this, you can check the Decidim documentation available here: https://docs.decidim.org/en/v0.27/customize/data_consent.html#_adding_scripts_which_require_data_consent

Please tell me if you have any questions!

2023-04-13 10:39 UTC, paulinebessoles approved these changes
Hi @AyakorK thank you for the PR! 
I have one feedback after reviewing in local, I think the Matomo cookie should appear on the cookie modal in the Analytics section, which is not the case right now:
<img width="607" alt="Capture d’écran 2023-04-13 à 12 36 00" src="https://user-images.githubusercontent.com/52420208/231733822-12dc12f3-046f-4731-903f-1199c5282c1e.png">

I think that in order to do this, you can check the Decidim documentation available here: https://docs.decidim.org/en/v0.27/customize/data_consent.html#_adding_scripts_which_require_data_consent

Please tell me if you have any questions!

2023-04-13 10:40 UTC, paulinebessoles requested changes
See my comment above

2023-04-13 13:55 UTC, paulinebessoles approved these changes

2023-04-13 14:53 UTC, luciegrau approved these changes

2023-04-14 12:58 UTC, Quentinchampenois approved these changes

2023-04-14 12:59 UTC, merged