preparation IH
OpenSourcePolitics/decidim-cese pull request #49
Opened 2023-05-09 12:53 UTC by eliegaboriau

This PR adds admin creation tasks and udpates CI/CD

2023-05-10 12:46 UTC, armandfardeau requested changes

2023-05-10 12:46 UTC, armandfardeau commented on .github/workflows/ci_cd.yml
> +    needs: [ lint, tests, test_build ]
```suggestion
    needs: [ lint, tests, system_tests, test_build ]
```

2023-05-10 12:46 UTC, armandfardeau commented on .github/workflows/ci_cd.yml
> +    needs: [ lint, tests, test_build ]
```suggestion
    needs: [ lint, tests, system_tests, test_build ]
```

2023-05-11 16:54 UTC, armandfardeau commented
Wait for https://github.com/mainio/decidim-module-term_customizer/pull/100 to be resolved

2023-05-12 11:24 UTC, armandfardeau requested changes

2023-05-12 11:24 UTC, armandfardeau commented on config/environments/production.rb
> +  config.deface.enabled = ENV['DEFACE_ENABLED'] == 'true'
```suggestion
  config.deface.enabled = ENV.fetch('DEFACE_ENABLED',  "false") == 'true'
```

2023-05-12 11:24 UTC, armandfardeau commented
@eliegaboriau Is this ready for review?

2023-05-12 12:56 UTC, eliegaboriau commented
Hello @armandfardeau , it is now

2023-05-12 13:23 UTC, Quentinchampenois approved these changes

2023-05-22 15:15 UTC, armandfardeau approved these changes

2023-05-22 15:15 UTC, merged