OVerride AH form view
OpenSourcePolitics/decidim-cese pull request #61
Opened 2023-07-12 13:02 UTC by Quentinchampenois

#### :tophat: Description
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?
- [Notion card]()

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access Backoffice
* Go to organization settings
* See ...

#### Tasks
- [ ] Add specs
- [ ] Add note about overrides in OVERLOADS.md
- [ ] In case of new dependencies or version bump, update related documentation

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2023-07-12 13:37 UTC, AyakorK approved these changes

2023-07-12 13:50 UTC, armandfardeau approved these changes

2023-07-12 14:18 UTC, Quentinchampenois commented
Changing approach because it breaks the date picker

2023-07-12 14:26 UTC, luciegrau requested changes
After product review, this PR is not validated from a functional point of view, since the modifications break the form's date picker. Plus, we need to make the modification on the module directly, rather than on the customer's repository.

2023-07-12 16:13 UTC, luciegrau reviewed
I tried locally and I found a problem: users can now fill the "City" field by themselves but after completing the zip code, the field becomes impossible to fill in again. Do you encounter the same issue? 

https://github.com/OpenSourcePolitics/decidim-cese/assets/87868063/c6a5b41c-36f0-42fb-b193-f1354bb0dc56

2023-07-13 08:09 UTC, luciegrau approved these changes

2023-07-13 08:12 UTC, merged